### ISSUE TITLE
Code for seg and detection

### ISSUE THREAD

**Issue by shunlinlu** [fuying-wang/MGCA#1]
Hi, authors

It's great to see your great and amazing work. I'm really impressed and thank you for sharing this clear repo. 

I was just wondering if it's possible to release the **code for segmentation and detection**. It gives me different results from your paper when I try to reproduce the results by myself.  It will be good if you can share this part so we can have a fair comparison. 

I really appreciate it.

**Comment by fuying-wang** [comment]
Hello,

Thanks for your interest in our work.
Yes. The detection and segmentation code and pre-trained models will be released later (before the end of this month).
