### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'num_devices'

### ISSUE THREAD

**Issue by umarikkar** [fuying-wang/MGCA#10]
Traceback (most recent call last):
  File "mgca_finetuner.py", line 121, in <module>
    cli_main()
  File "mgca_finetuner.py", line 112, in cli_main
    tuner.training_steps = tuner.num_training_steps(trainer, datamodule)
  File "/vol/research/fmodel_medical/people/umar/mm_cxr/repos_lit_review/MGCA/mgca/models/ssl_finetuner.py", line 144, in num_training_steps
    effective_batch_size = trainer.accumulate_grad_batches * trainer.num_devices
**AttributeError: 'Trainer' object has no attribute 'num_devices'**

Hi, the pytorch lightning class 'Trainer' does not create the attribute num_devices. Should I set trainer.num_devices=args.gpus manually?

**Comment by fuying-wang** [comment]
Hi,

Could you try updating the version of pytorch_lightning? 

```
pip install pytorch_lightning --upgrade
```

**Comment by umarikkar** [comment]
![image](https://user-images.githubusercontent.com/55051239/217217539-fdbfeaed-4d93-4527-a68c-22cb61391bf7.png)

Thanks for the reply, I updated to 1.9.0. However the pre-trained checkpoint I saved is when version 1.5.0 was used and it does not seem compatible. Would it be possible to upload your checkpoints on the google drive?

**Comment by umarikkar** [comment]
I switched back to 1.5.10 and it works as before. However as you mentioned trainer.num_devices isn't defined.

**Comment by fuying-wang** [comment]
I understand. Could you try changing the function `num_training_steps` as follows?
```
    @staticmethod
    def num_training_steps(trainer, dm) -> int:
        """Total training steps inferred from datamodule and devices."""
        dataset = dm.train_dataloader()
        dataset_size = len(dataset)
        num_devices = max(1, trainer.num_gpus, trainer.num_processes)
        if trainer.tpu_cores:
            num_devices = max(num_devices, trainer.tpu_cores)
        effective_batch_size = trainer.accumulate_grad_batches * num_devices

        return (dataset_size // effective_batch_size) * trainer.max_epochs
```

**Comment by umarikkar** [comment]
this works. Thanks, I see this is the same function used in ssl_detector.
