### ISSUE TITLE
non-deterministic implementation of some lines unreachable.

### ISSUE THREAD

**Issue by umarikkar** [fuying-wang/MGCA#11]
**Exception has occurred: RuntimeError**
cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

line 75 in ssl_finetuner.py

This does not work even when turning torch.backends.cudnn.deterministic = False

**Comment by umarikkar** [comment]
![Screenshot from 2023-02-06 16-16-52](https://user-images.githubusercontent.com/55051239/217025464-e5fbe48f-49d3-4a98-9f96-3bb6dffa8473.png)

**Comment by fuying-wang** [comment]
Hi, 

Could you try to set the `args.deterministic = Fasle` in Line 476 of `mgca/models/mgca/mgca_module.py`?

**Comment by umarikkar** [comment]
Hi, it does not work unfortunately. I can make it work by setting torch.use_deterministic_algorithms(True, warn_only=True) in the validation step and test step functions inside SSLFinetuner class.

![image](https://user-images.githubusercontent.com/55051239/217223495-21d1b222-d5e9-42bd-9953-c4b008f1fbee.png)

**Comment by cheliu-computation** [comment]
Hi, I have got this issue as well, I fixed this issue when I add 'torch.use_deterministic_algorithms(False)' in the file which you called from torchmetric. However, this operation would change the randomness every run time. So I think it gives more uncertainty when we reproduce this work. I also unable to reach '87.6' AUC on 0.01 CheXpert, and different result on segmentation and detection as well.

**Comment by fuying-wang** [comment]
Hi,

Which version of PyTorch and pytorch_lightning are you using?

**Comment by cheliu-computation** [comment]
> Hi,
> 
> Which version of PyTorch and pytorch_lightning are you using?

Thanks for your reply. 
I am using pytorch_lightning 1.5.10, and pytorch 1.13.1. The pytorch_lightning version matches the 'requirement.txt', but the pytorch version is not mentioned in this file, so I use the stable version for 3090.
I think the issue is torchmetric, rather than lightning or torch, and I use torchmetric 0.8.2 following the requirement file.

**Comment by fuying-wang** [comment]
Hi, 

I use `torch==1.12.1+cu113` and I didn't have this problem. Other packages are the same as yours. You may also try updating torchmetrics if you think there is a problem.

**Comment by nguyenpbui** [comment]
Hello @cheliu-computation ,

Did you resolve this problem? I am also unable to reproduce the results of the segmentation task.
The reproduced results are much lower than the reported ones in the paper.
