### ISSUE TITLE
positional embedding

### ISSUE THREAD

**Issue by MoramiSu** [fuying-wang/MGCA#13]
Dear Author,

Thank you for your work! However, I met some problems when I runing this code. In the forward part of BertEncoder (line 379 in Encoder.py), it looks like that you used token_type_ids as position_ids, but the token_type_ids is an all zero tensor. Maybe it should be changed into a relative positonal ids?

Sincerely,
Morami

**Comment by fuying-wang** [comment]
Hi Morami,

Thanks very much for pointing out!

Yes. It might be more reasonable to use relative positional ids.

Best regards,
Fuying
