### ISSUE TITLE
mimic_cxr_sectioned.csv

### ISSUE THREAD

**Issue by cl-red** [fuying-wang/MGCA#16]
你好，我想问以下关于在mgca/constants.py文件中MIMIC_CXR_TEXT_CSV = MIMIC_CXR_DATA_DIR / "mimic_cxr_sectioned.csv"中的“mimic_cxr_sectioned.csv”在哪里获得，我在mimic-cxr-jpg和mimic-cxr两个数据库中并没有看到

**Comment by gentlefress** [comment]
请问这个数据集你下载好了吗，可以分享一下吗？

**Comment by fuying-wang** [comment]
可以通过运行：
```
cd mgca/preprocess
python mimic_cxr.py
```
生成这两个文件。
不过需要将`mimic_cxr.py`中的`extract_text = False`改为`extract_text = True`。
具体生成的函数在这里：https://github.com/HKU-MedAI/MGCA/blob/b9ec84f378e9561628c30f39d5ee64250f450f37/mgca/preprocess/utils.py#L20
