### ISSUE TITLE
Hello, I would like to ask how long it takes to train MIMIC-CXR-JPG with two RTX 3090 used in the pre-training process? This will help me a lot, thanks. Also, I want to ask what is the size of MIMIC-CXR-JPG?

### ISSUE THREAD

**Issue by cl-red** [fuying-wang/MGCA#2]
Hello, I would like to ask how long it takes to train MIMIC-CXR-JPG with two RTX 3090 used in the pre-training process? This will help me a lot, thanks. Also, I want to ask what is the size of MIMIC-CXR-JPG?

**Comment by fuying-wang** [comment]
Hi,

The training process takes about 1 day (~ 24 hours). After preprocessing, we have about 217k image-text pairs for pre-training.

**Comment by cl-red** [comment]
Ha ha，can 217k image-text pairs train so fast on two RTX 3090? What a surprise！
Thank you！

**Comment by nguyenpbui** [comment]
Hello @fuying-wang , 

Congrats on your awesome work!

Currently, I am using an A100 80GB GPU to reproduce your results. 
In my system, it takes more than 1 hour for one epoch (70 minutes) with a batch size of 256. 
I tested with two encoder backbones (ResNet50 and ViT_base) but the training times are similar.

You only use 2 RTX 3090 24GB GPU for pre-training and it only takes one day to finish. 
Can you share some thoughts on the slow training process?

Thank you very much.
