### ISSUE TITLE
Using other datasets

### ISSUE THREAD

**Issue by jiangcaoz** [fuying-wang/MGCA#20]
你好，我发现pretrain_dataset.py文件里面目前还是只针对MIMIC-CXR数据集，请问如果我想使用其它数据集(例如RSNA数据集)时我应该如何对pretrain_dataset.py文件进行修改？或者我遗漏了些什么？

**Comment by fuying-wang** [comment]
下游任务的数据集在classification_dataset.py里面

**Comment by YH-2023** [comment]
> MIMIC-CXR

MIMIC-CXR数据集太大无法下载，可以使用其他数据集代替吗？
