### ISSUE TITLE
跑自己的数据集

### ISSUE THREAD

**Issue by inhaowu** [fuying-wang/MGCA#22]
在阅读完您的论文后，对我深感启发！请问如果想要把代码适配到自己的数据集中（其他疾病），是否就不需要预训练了呢？请问将该代码迁移到其他疾病里的数据集中也可以运用吗？

**Comment by Rubiscol** [comment]
不需要了吧，但是最好需要FINETUNE 一下

**Comment by fuying-wang** [comment]
是的，迁移过去可以用一小部分数据finetune一下

**Comment by inhaowu** [comment]
> 
您好！可以再具体问一下吗。我的任务其实是椎骨检测，和您论文里的可能差距较大，而且文本信息也与您训练的文本数据差距较大，这样在一小部分数据上finetune也是可行的吗？

**Comment by fuying-wang** [comment]
你好！ 这样可能不行，这个model主要是针对chest X-ray的

**Comment by inhaowu** [comment]
> 你好！ 这样可能不行，这个model主要是针对chest X-ray的

好的，谢谢！
