### ISSUE TITLE
Ablation experiments

### ISSUE THREAD

**Issue by Eldo-rado** [fuying-wang/MGCA#23]
Hi, thanks for your contributions!
I was wondering if you do any ablation experiments with different granularity? (e.g. only use CTA/ITA/CPA)

**Comment by fuying-wang** [comment]
Yes. Please check Table 4 of the paper.

**Comment by Eldo-rado** [comment]
> Yes. Please check Table 4 of the paper.

Thanks, I didn't see it before. Thank you again
