### ISSUE TITLE
About the activation map

### ISSUE THREAD

**Issue by o0t1ng0o** [fuying-wang/MGCA#24]
Hi @fuying-wang,

Thank you for sharing this code.
I am wondering how to generate the activation map in Figure 3?
Could you please give an example?

Thanks.
![image](https://github.com/HKU-MedAI/MGCA/assets/16815652/8a498560-b978-4e5a-a557-a9f5cde588e9)

**Comment by fuying-wang** [comment]
Sure. It will be uploaded in recent few days.

**Comment by o0t1ng0o** [comment]
Thank you very much!

**Comment by tzcskys** [comment]
> Sure. It will be uploaded in recent few days.

Hi, amazing job and thanks for sharing. May I ask whether the visualization code has been uploaded? Thanks.

**Comment by fuying-wang** [comment]
Hi all,

Sorry for the late update. Please find the visualization code in https://github.com/HKU-MedAI/MGCA/blob/main/mgca/visualization/visualize_attention_map.ipynb. 
Hope it helps!

**Comment by tzcskys** [comment]
@fuying-wang Hi thanks for your sharing, may I ask why you use 1-word_atten[img_idx] in this file? normally higher values indicates higher importance.
