### ISSUE TITLE
About the pretrained model of text encoder

### ISSUE THREAD

**Issue by o0t1ng0o** [fuying-wang/MGCA#25]
Hi @fuying-wang,

I found that you share the pretrained model of image encoder, such as resnet-50 and vit-base.
Could you please share the pretrained model for text encoder?
Thank you in advance!
![image](https://github.com/HKU-MedAI/MGCA/assets/16815652/b5742176-f074-476a-a182-b61c423c6e40)

**Comment by fuying-wang** [comment]
Hello,

These are the pretrained weights of the whole model. Could you try load it with 
```model = MGCA.load_from_checkpoint(args.path, strict=False)```?
The name denotes the visual encoder it used.

**Comment by o0t1ng0o** [comment]
Thank you very much!
I load it successfully.
