### ISSUE TITLE
SIIM-stage1 dataset can't download

### ISSUE THREAD

**Issue by cl-red** [fuying-wang/MGCA#27]
I have trouble downloading SIIM data set, I can't use google cloud to download siim-stage1 part of the data set, could you please provide a link to SIIM data set web disk? Thank you very much

**Comment by fuying-wang** [comment]
Hello,

Please find the SIIM dataset here: https://drive.google.com/file/d/1zQn32V8fjYeWkDvfspQU1yHx_R1xIUp4/view
