### ISSUE TITLE
分享数据集

### ISSUE THREAD

**Issue by hnjzbss** [fuying-wang/MGCA#28]

**Comment by hnjzbss** [comment]
您好，感谢您分享这么优秀的工作，我想follow您的工作，并用自己的算法跑一下COVIDx6这个数据集，但在您提供的链接里已经下载不到这个版本的数据了，新版本的数据缺少很多图片。可以麻烦您分享一下COVIDx6数据集吗，非常感谢！

**Comment by hnjzbss** [comment]
您好，感谢您分享这么优秀的工作，我想follow您的工作，并用自己的算法跑一下COVIDx6这个数据集，但在您提供的链接里已经下载不到这个版本的数据了，新版本的数据缺少很多图片。可以麻烦您分享一下COVIDx6数据集吗，非常感谢！

**Comment by SinuoWang** [comment]
同求 ~

**Comment by fuying-wang** [comment]
不好意思回复有点晚。数据可以在这里访问。
https://connecthkuhk-my.sharepoint.com/:u:/g/personal/fuyingw_connect_hku_hk/EccxzpOVTwNNlyFpGIF5FDwBDbyOiCs9BT1cbcrqgtch8A?e=lvfqfK
