### ISSUE TITLE
Hello, could you please give me the url of the dataset of MIMIC-CXR 2.0.0? Because the application process of this dataset is really troublesome.

### ISSUE THREAD

**Issue by cl-red** [fuying-wang/MGCA#3]
Hello, could you please give me the url of the dataset of MIMIC-CXR 2.0.0? Because the application process of this dataset is really troublesome.

**Comment by fuying-wang** [comment]
Hello,

You can download the MIMIC-CXR in the official website (https://physionet.org/content/mimic-cxr/2.0.0/). 
We don't have an extra link to download this data.
