### ISSUE TITLE
I encountered a problem. When my code is running, the system often freezes. Have you ever encountered a similar situation?

### ISSUE THREAD

**Issue by cl-red** [fuying-wang/MGCA#30]

**Comment by cl-red** [comment]
My configuration is RTX4090, and the memory and CPU are not loaded.

**Comment by fuying-wang** [comment]
Sorry, I didn't have this problem before. I am not sure what's wrong with it.

**Comment by cl-red** [comment]
It‘s my problem. I've solved it.
