### ISSUE TITLE
Problems with the file path in constants.py and pretrain_dataset.py

### ISSUE THREAD

**Issue by RuoxiangXu** [fuying-wang/MGCA#34]
Thanks for your great work! Some problems about file path when I tried to reproduce the pre-training part.
```python
# constants.py line 5
DATA_BASE_DIR = os.path.join(os.path.dirname(
    os.path.abspath(__file__)), "../../data")
``` 
The above code will make DATA_BASE_DIR to be directly: "current_path../../data" which is an invalid path. If intended to access the "data" folder in the upper upper directory, the code should be:
```python
DATA_BASE_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), "../../data"))
``` 
Also:
```python
# pretrain_dataset.py line 47
filepath = os.path.join(
            BASE_DIR, "../../data/captions.pickle")
``` 
may cause same problem.

In the  README file, I kindly suggest to add a reminder to check also the path of pretrain_dataset.py line 47 except for that of constants.py.

**Comment by fuying-wang** [comment]
Thanks for the reminder! The README.md has been updated.

**Comment by RuoxiangXu** [comment]
Another path need checking:
line 503 of `mgca_module.py` :)

**Comment by fuying-wang** [comment]
Updated!
