### ISSUE TITLE
Request for Access to Object-CXR Dataset

### ISSUE THREAD

**Issue by lichencan** [fuying-wang/MGCA#35]
Your project utilizes the Object-CXR dataset, but I am currently unable to download it from the public internet. The previously available Baidu Pan or Google Drive links are now empty. Could you possibly provide this dataset to enable a more straightforward replication of the model's results presented in your project?

**Comment by fuying-wang** [comment]
Could you try this? https://academictorrents.com/details/fdc91f11d7010f7259a05403fc9d00079a09f5d5
