### ISSUE TITLE
The csv files in constrants.py

### ISSUE THREAD

**Issue by LijunRio** [fuying-wang/MGCA#4]
Dear author, 
Hi! Thank you for your work! Could you please publish master.csv, train.csv and test.csv? Or tell me the format of these files? Looking forward to your reply !
Sincerely

**Comment by fuying-wang** [comment]
Hello,

You can run the Python code `mgca/preprocess/mimic_cxr.py` to create these files.

Thanks a lot!

**Comment by LijunRio** [comment]
Dear author,
Thanks for your quick and kind reply! 
Sincerely
