### ISSUE TITLE
AttributeError: 'MGCA' object has no attribute 'img_queue'

### ISSUE THREAD

**Issue by LijunRio** [fuying-wang/MGCA#6]
Dear Author,

When I am training the mgca_module.py, I met the problem "**AttributeError: 'MGCA' object has no attribute 'img_queue'**". Could you give me some advices for solving this issue? I'm looking for your reply.

Sincerely,
Jun

**Comment by fuying-wang** [comment]
Hi Jun,

Please pull the latest code and try again!

Thanks a lot!

**Comment by LijunRio** [comment]
Dear Author,


The problem have been solved. Thanks for your quick reply !


Sincerely,


Jun Li
| |
黎郡 2016113015
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/2/2022 10:48，Fuying ***@***.***> wrote：

Hi Jun,

Please pull the latest code and try again!

Thanks a lot!
