### ISSUE TITLE
AttributeError: 'MGCA' object has no attribute 'checkpoint_callback'

### ISSUE THREAD

**Issue by LijunRio** [fuying-wang/MGCA#7]
Dear Author,

Thank you for your work! However, when I reproduce this code, I met the problem "AttributeError: 'MGCA' object has no attribute 'checkpoint_callback'".  Could you help me fix this bug?

Sincerely, 
Jun

**Comment by fuying-wang** [comment]
Hi Jun,

Thanks for pointing that out!

We have fixed this bug in the latest code. Please try again.

Thanks a lot!
