### ISSUE TITLE
mimic-cxr-master?

### ISSUE THREAD

**Issue by umarikkar** [fuying-wang/MGCA#9]
I cannot find the mimic-cxr-master or mimic-cxr-train and test files. They aren't there in the physionet website

**Comment by umarikkar** [comment]
Solved:

**run** mgca/preprocess/mimic_cxr.py

make sure you have saved **mimic_cxr_sectioned.csv** by running [this script](https://github.com/MIT-LCP/mimic-cxr/tree/master/txt/create_section_files.py) first.

**Comment by cl-red** [comment]
Hi, I wanted to ask how to obtain mimic_cxr_sectioned.csv file, but I didn't see it.

**Comment by fuying-wang** [comment]
You can change `extract_text=True` and run this code:
```
mgca/preprocess/mimic_cxr.py
```
